### PR TITLE
Add ThrottleAsyncSequence & AnyAsyncSequence<Element>

### PR DESCRIPTION
**Pull request by m1entus**
This PR adds `ThrottleAsyncSequence` & `AnyAsyncSequence<Element>` which allows to represent AsyncSequence in simmilar way as in Combine `AnyPublisher` without need to specify Concrete type of sequence.

### CODE REVIEW

**Comment by m1entus** [comment]
Ah i see that you have added `AnyAsyncSequenceable` two days ago 🤓 So only `ThrottleAsyncSequence` make sense to add

**Comment by reddavis** [comment]
Hey! Amazing thankyou! `ThrottleAsyncSequence` looks great!

Haha yer, I added `AnyAsyncSequenceable` and also `AnyThrowingAsyncSequenceable` for those sequences that can throw.

Imma just on holiday atm, but once back I'll have a proper look and merge in!

**Comment by m1entus** [comment]
> Hey! Amazing thankyou! `ThrottleAsyncSequence` looks great!
> 
> Haha yer, I added `AnyAsyncSequenceable` and also `AnyThrowingAsyncSequenceable` for those sequences that can throw.
> 
> Imma just on holiday atm, but once back I'll have a proper look and merge in!

Sure np. take a rest!

**Comment by m1entus** [comment]
Closing this one

**Pull request closed without merging**
